-- SQL PROBLEM 2
-- VICTOR CHAVEZ

SELECT *FROM INGREDIENT;
SELECT* FROM INVENTORY;

SELECT INGRED_NAME, 
INVT_QTY,
INVT_MIN_STOCK
FROM  INGREDIENT IG
JOIN INVENTORY IV ON IG.INVT_ID = IV.INVT_ID
WHERE IV.INVT_QTY < IV.INVT_MIN_STOCK;
