-- SQL PROBLEM 2
-- VICTOR CHAVEZ

-- Inventory Shortage Alert (VICTOR) 
-- Query: List all ingredients that are below the minimum stock level in the inventory.  
-- Entities Involved: INGREDIENT, INVENTORY  

SELECT INGRED_NAME, 
INVT_QTY,
INVT_MIN_STOCK
FROM  INGREDIENT IG
JOIN INVENTORY IV ON IG.INVT_ID = IV.INVT_ID
WHERE IV.INVT_QTY < IV.INVT_MIN_STOCK;

-- TO FIND THE TAXES COLLECTED FIRST FIND THE COMMON COLUMN BY RUNNING
-- SELECT *FROM INGREDIENT;
-- SELECT* FROM INVENTORY;

-- NEXT SELECT GTHE COLOMNS NEEDED AND JOIN THEM ON A TABLE BY ADDING 
-- SELECT INGRED_NAME, 
-- INVT_QTY,
-- INVT_MIN_STOCK
-- FROM  INGREDIENT IG
-- JOIN INVENTORY IV ON IG.INVT_ID = IV.INVT_ID

-- FINALLY ADD THE WHERE FUNCTION THAT COMPARES THE CURRENT INVENTORY AGAINST THE MINIMUM STOCK BY ADDING THE WHERE FUNCTION
-- WHERE IV.INVT_QTY < IV.INVT_MIN_STOCK;
