-- SQL PROBLEM 9
-- VICTOR CHAVEZ

-- Tax Collection Report 
-- Query: Generate a monthly report showing the total tax collected, broken down by tax type.  Entities Involved: TAX, PAYMENT, SALES_REPORT  

SELECT TAX_NAME, TAX_RATE, SUM(ROUND((TAX_RATE * PAY_AMOUNT), 2)) AS TAX_COLLECTED
FROM TAX T 
JOIN PAYMENT P ON T.TAX_ID = P.TAX_ID
WHERE PAY_DATE >= DATE_FORMAT(CURDATE() - INTERVAL 1 MONTH, '%Y-%m-01') AND PAY_DATE < DATE_FORMAT(CURDATE(), '%Y-%m-01')
GROUP BY T.TAX_ID
ORDER BY TAX_COLLECTED DESC;

-- TO FIND THE TAXES COLLECTED FIRST FIND THE COMMON COLUMN BY RUNNING
-- SELECT * FROM TAX;
-- SELECT * FROM PAYMENT;
-- SELECT * FROM SALES_REPORT;

-- NEXT FIND THE TAX_RATE FROM AND NAME FROM THE TAX TABLE BY RUNNING THE FOLLOWING
-- SELECT T.TAX_RATE, T.TAX_NAME 
-- FROM TAX T 
-- JOIN PAYMENT PMT ON T.TAX_ID = PMT.TAX_ID
-- JOIN SALES_REPORT SR ON SR.PAY_ID = PMT.PAY_ID;

-- FIND THE TOTAL TAXES COLLECTED BY MULTIPLYING THE AMOUNT PAID BY THE TAX RATE USING 
-- SUM(ROUND(PMT.PAY_AMOUNT * T.TAX_RATE,2)) AS "TAXES COLLECTED"


-- FIND THE TAXES COLLECTED FOR THE SPECIFIC MONTH USING GTHE WHERE FUNCTION
-- WHERE PAY_DATE >= DATE_FORMAT(CURDATE() - INTERVAL 1 MONTH, '%Y-%m-01') AND PAY_DATE < DATE_FORMAT(CURDATE(), '%Y-%m-01')

-- FINALLY GROUP ALL THE TAXES BY TAX ID AND GROUP THEM IN ORDER BY THE DESCRIPTION USING
-- GROUP BY T.TAX_ID
-- ORDER BY TAX_COLLECTED DESC;
