-- SQL PROBLEM 9
-- VICTOR CHAVEZ

-- Tax Collection Report 
-- Query: Generate a monthly report showing the total tax collected, broken down by tax type.  Entities Involved: TAX, PAYMENT, SALES_REPORT  

SELECT T.TAX_ID, T.TAX_NAME, SUM(ROUND(PMT.PAY_AMOUNT * T.TAX_RATE,2)) AS "TAXES COLLECTED" 
FROM TAX T
JOIN PAYMENT PMT ON T.TAX_ID = PMT.TAX_ID
GROUP BY T.TAX_NAME; 

-- TO FIND THE TAXES COLLECTED FIRST FIND THE COMMON COLUMN BY RUNNING
-- SELECT * FROM TAX;
-- SELECT * FROM PAYMENT;
-- SELECT * FROM SALES_REPORT;

-- NEXT FIND THE TAX_RATE FROM AND NAME FROM THE TAX TABLE BY  RUNNING THE FOLLOWING
-- SELECT T.TAX_RATE, T.TAX_NAME 
-- FROM TAX T 
-- JOIN PAYMENT PMT ON T.TAX_ID = PMT.TAX_ID
-- JOIN SALES_REPORT SR ON SR.PAY_ID = PMT.PAY_ID;

-- FINALLY FIND THE TOTAL TAXES COLLECTED BY ADDING 
-- SUM(ROUND(PMT.PAY_AMOUNT * T.TAX_RATE,2)) AS "TAXES COLLECTED"
-- GROUP BY T.TAX_NAME; 
