-- BUDGET
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS BUDGET (
    BUDGET_ID INT UNSIGNED,
    FISCAL_YEAR SMALLINT NOT NULL,
    ALLOCATED_AMT DECIMAL(10,2) NOT NULL,
    REMAINING_AMT DECIMAL(10, 2) NOT NULL,
    BUDGET_STATUS VARCHAR(25) NOT NULL,
    DEPT_ID INT UNSIGNED,
    PRIMARY KEY (BUDGET_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID) ON UPDATE CASCADE
    
    );
    
SELECT * FROM BUDGET;

ALTER TABLE BUDGET
MODIFY REMAINING_AMT DECIMAL(10, 2);
