-- CARD_ISSUER
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS CARD_ISSUER (
	CARD_ID INT UNSIGNED,
    CARD_TYPE VARCHAR(25) NOT NULL,
    ISSUING_BANK VARCHAR(255),
    PRIMARY KEY (CARD_ID)
    );

SELECT * FROM CARD_ISSUER
