-- CATERING
-- MAYBELLINE

CREATE TABLE IF NOT EXISTS CATERING(
CATER_CODE INT UNSIGNED,
CATER_TYPE VARCHAR(255) NOT NULL,
CATER_REVENUE DECIMAL(10,2) NOT NULL,
EVENT_CODE INT UNSIGNED,
PRIMARY KEY (CATER_CODE),
FOREIGN KEY(EVENT_CODE) REFERENCES EVENT(EVENT_CODE) ON UPDATE CASCADE
);

SELECT * FROM CATERING;
