-- CERTIFICATION
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS CERTIFICATION(
	CERT_ID INT UNSIGNED,
    CERT_NAME VARCHAR(255) NOT NULL,
    RENEWAL_PERIOD SMALLINT NOT NULL,
	ISSUED_BY VARCHAR(255) NOT NULL,
    TRAIN_CODE INT UNSIGNED,
    PRIMARY KEY (CERT_ID),
    FOREIGN KEY (TRAIN_CODE) REFERENCES TRAINING (TRAIN_CODE) ON UPDATE CASCADE
    
    );
SELECT * FROM CERTIFICATION
