-- CUSTOMER_CARD
-- MAYBELLINE

CREATE TABLE IF NOT EXISTS CUSTOMER_CARD(
	CUST_CARD_ID INT UNSIGNED,
    CARD_NUM VARCHAR(16) NOT NULL,
    CARD_FNAME VARCHAR(255) NOT NULL,
    CARD_LNAME VARCHAR(255) NOT NULL,
    CARD_INITIAL CHAR(1),
    CARD_BALANCE DECIMAL(20,2) NOT NULL,
    EXP_DATE DATE NOT NULL,
    CARD_ID INT UNSIGNED, 
    CUST_ID INT UNSIGNED,
    PRIMARY KEY(CUST_CARD_ID),
    FOREIGN KEY (CARD_ID) REFERENCES CARD_ISSUER(CARD_ID) ON UPDATE CASCADE,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE
);

SELECT * FROM CUSTOMER_CARD;

