-- CUSTOMER_EVENT
-- MAYBELLINE

CREATE TABLE IF NOT EXISTS CUSTOMER_EVENT(
EVENT_CODE INT UNSIGNED,
CUST_ID INT UNSIGNED,
RSVP CHAR(1) NOT NULL,
TIME TIME,
PRIMARY KEY(EVENT_CODE,CUST_ID),
FOREIGN KEY (EVENT_CODE) REFERENCES EVENT(EVENT_CODE) ON DELETE CASCADE,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON DELETE CASCADE
);

SELECT * FROM CUSTOMER_EVENT;