-- DEPARTMENT
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS DEPARTMENT (
	DEPT_ID INT UNSIGNED,
    DEPT_LOCATION VARCHAR(255) NOT NULL,
    DEPT_NAME VARCHAR(255) NOT NULL,
    DEPT_TYPE VARCHAR (255) NOT NULL,
    PRIMARY KEY (DEPT_ID)
    
    );
    SELECT * FROM DEPARTMENT
