-- DEPARTMENT_INVENTORY
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS DEPARTMENT_INVENTORY(
	INVT_ID INT UNSIGNED,
    DEPT_ID INT UNSIGNED, 
    DATE_ADDED DATE NOT NULL,
    QUANTITY SMALLINT NOT NULL,
    PRIMARY KEY (INVT_ID,DEPT_ID),
    FOREIGN KEY (INVT_ID) REFERENCES INVENTORY (INVT_ID) ON DELETE CASCADE,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID) ON DELETE CASCADE
    );
SELECT * FROM DEPARTMENT_INVENTORY
