-- EMPLOYEE_TRAINING
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS EMPLOYEE_TRAINING (
	EMP_ID INT UNSIGNED,
    TRAIN_CODE INT UNSIGNED,
    DATE_STARTED DATE NOT NULL,
    PRIMARY KEY (EMP_ID, TRAIN_CODE),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE,
	FOREIGN KEY (TRAIN_CODE) REFERENCES TRAINING (TRAIN_CODE) ON DELETE CASCADE

    );
SELECT * FROM EMPLOYEE_TRAINING
