-- EMPLOYEE_SHIFT
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS EMPLOYEE_SHIFT (
	ATTEND_ID INT UNSIGNED,
    SHIFT_ID INT UNSIGNED,
    EMP_ID INT UNSIGNED,
    PRIMARY KEY (ATTEND_ID),
    FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT (SHIFT_ID) ON UPDATE CASCADE,
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON UPDATE CASCADE

    );
SELECT * FROM EMPLOYEE_TRAINING
