-- EMPLOYEE
-- EMPLOYEE
-- Angelo Angel

CREATE TABLE IF NOT EXISTS EMPLOYEE (
	EMP_ID INT UNSIGNED,
    EMP_FNAME VARCHAR(255) NOT NULL,
    EMP_LNAME VARCHAR(255) NOT NULL,
    EMP_INITAL CHAR(1),
    EMP_PHONE VARCHAR(255) NOT NULL,
    EMP_EMAIL VARCHAR(255) NOT NULL,
    EMP_ADDRESS VARCHAR(255) NOT NULL,
    EMP_HIRE_DATE DATE NOT NULL,
    ZIP_CODE INT UNSIGNED,
    ROLE_ID INT UNSIGNED,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (ZIP_CODE) REFERENCES ZIP (ZIP_CODE) ON UPDATE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID) ON UPDATE CASCADE
);

SELECT * FROM EMPLOYEE;