-- EMPLOYEE_CERTIFICATION
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS EMPLOYEE_CERTIFICATION(
	EMP_ID INT UNSIGNED,
    CERT_ID INT UNSIGNED,
    DATE_RECEIVED DATE NOT NULL,
    VALID_UNTIL DATE,
    PRIMARY KEY (EMP_ID, CERT_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON DELETE CASCADE,
	FOREIGN KEY (CERT_ID) REFERENCES CERTIFICATION (CERT_ID) ON DELETE CASCADE
    
    
    );
SELECT * FROM EMPLOYEE_CERTIFICATION
