-- EQUIPMENT
-- Angelo Angel

CREATE TABLE IF NOT EXISTS EQUIPMENT (
	EQUIP_ID INT UNSIGNED,
    EQUIP_NAME VARCHAR(255) NOT NULL,
    EQUIP_TYPE VARCHAR(255) NOT NULL,
    EQUIP_MODEL VARCHAR(255) NOT NULL,
    EQUIP_MAKE VARCHAR(255) NOT NULL,
    INVT_ID INT UNSIGNED,
    SUPP_ID INT UNSIGNED,
    PRIMARY KEY (EQUIP_ID),
    FOREIGN KEY (INVT_ID) REFERENCES INVENTORY (INVT_ID) ON UPDATE CASCADE, -- one-to-one
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID) ON UPDATE CASCADE
);

-- Enforces one-to-one relationship and ensures no duplicates of the foreign key exists
ALTER TABLE EQUIPMENT
ADD UNIQUE (INVT_ID);

SELECT * FROM EQUIPMENT;
