-- EXPENSE
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS EXPENSE (
	EXPENSE_ID INT UNSIGNED,
    EXPENSE_DATE DATE,
    EXPENSE_CAT VARCHAR(50),
    EMPENSE_AMT DECIMAL(15,2) NOT NULL,
	TAX_ID INT UNSIGNED,
	COMP_CARD INT UNSIGNED,
    DEPT_ID INT UNSIGNED,
    PRIMARY KEY (EXPENSE_ID),
    FOREIGN KEY (TAX_ID) REFERENCES TAX (TAX_ID) ON UPDATE CASCADE,
	FOREIGN KEY (COMP_CARD) REFERENCES COMPANY_CARD (COMP_CARD) ON UPDATE CASCADE,
	FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID) ON UPDATE CASCADE
    
    );
SELECT * FROM EXPENSE
