-- GIFT_CARD
-- Angelo Angel

CREATE TABLE IF NOT EXISTS GIFT_CARD (
	GC_ID INT UNSIGNED,
    GC_NUM VARCHAR(255) NOT NULL,
    GC_BALANCE DECIMAL(10, 2) NOT NULL,
    DATE_CREATED DATE NOT NULL,
    EXP_DATE DATE NOT NULL,
    CUST_ID INT UNSIGNED,
    PRIMARY KEY (GC_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE CASCADE
);

SELECT * FROM GIFT_CARD;