-- INVOICE
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS INVOICE (
	INVOICE_ID INT UNSIGNED,
    INVOICE_DATE DATE NOT NULL,
	SUPP_ID INT UNSIGNED,
	EXPENSE_ID INT UNSIGNED,
    PRIMARY KEY (INVOICE_ID),
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID) ON UPDATE CASCADE,
	FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSE (EXPENSE_ID) ON UPDATE CASCADE
    
    );
SELECT * FROM INVOICE
