-- INVOICE_LINE
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS INVOICE_LINE (
	INVT_ID INT UNSIGNED,
	INVOICE_ID INT UNSIGNED,
    QUANTITY SMALLINT NOT NULL,
    PRIMARY KEY (INVT_ID, INVOICE_ID),
    FOREIGN KEY (INVT_ID) REFERENCES INVENTORY (INVT_ID) ON DELETE CASCADE,
	FOREIGN KEY ( INVOICE_ID) REFERENCES INVOICE (INVOICE_ID) ON DELETE CASCADE
    
    );

SELECT * FROM INVOICE_LINE
