-- LOYALTY_PROGRAM
-- Angelo Angel

-- CUST is both PK and FK

CREATE TABLE IF NOT EXISTS LOYALTY_PROGRAM (
	CUST_ID INT UNSIGNED,
    JOIN_DATE DATE NOT NULL,
    LP_STATUS VARCHAR(10) NOT NULL,
    POINTS INT NOT NULL,
    EXP_DATE DATE NOT NULL,
    PRIMARY KEY (CUST_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON DELETE CASCADE
);

-- Enforces one-to-one relationship and ensures no duplicates of the foreign key exists
ALTER TABLE LOYALTY_PROGRAM
ADD UNIQUE (CUST_ID);

SELECT * FROM LOYALTY_PROGRAM;