-- NUTRITIONAL_INFO
-- MAYBELLINE

CREATE TABLE IF NOT EXISTS NUTRITIONAL_INFO(
    PROD_ID INT UNSIGNED,
    SERV_SIZE VARCHAR(50) NOT NULL,
    CALORIES DECIMAL(5,2) NOT NULL,
    TOTAL_FAT_g DECIMAL(5,2) NOT NULL,
    SAT_FAT_g DECIMAL(5,2) NOT NULL,
    CHOLESTEROL_mg DECIMAL(5,2) NOT NULL,
    SODIUM_mg DECIMAL(5,2) NOT NULL,
    PRIMARY KEY(PROD_ID),
    FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE CASCADE
);
SELECT * FROM NUTRITIONAL_INFO;

ALTER TABLE NUTRITIONAL_INFO
ADD UNIQUE(PROD_ID);
