-- ORDER_LINE
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS ORDER_LINE (
	ORDER_ID INT UNSIGNED,
    PROD_ID INT UNSIGNED, 
    QUANTITY SMALLINT NOT NULL,
    PRIMARY KEY (ORDER_ID,PROD_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES PLACED_ORDER (ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID) ON DELETE CASCADE
    );
SELECT * FROM ORDER_LINE
