-- PAYMENT
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS PAYMENT(
	PAY_ID INT UNSIGNED,
    PAY_DATE DATE NOT NULL,
    PAY_AMOUNT DECIMAL (7,2),
	PAY_METHOD VARCHAR(20) NOT NULL,
    TAX_ID INT UNSIGNED,
    CUST_CARD_ID INT UNSIGNED,
	ORDER_ID INT UNSIGNED,
    PRIMARY KEY (PAY_ID),
    FOREIGN KEY (TAX_ID) REFERENCES TAX (TAX_ID) ON UPDATE CASCADE,
	FOREIGN KEY (CUST_CARD_ID) REFERENCES CUSTOMER_CARD (CUST_CARD_ID) ON UPDATE CASCADE,
    FOREIGN KEY (ORDER_ID) REFERENCES PLACED_ORDER (ORDER_ID) ON UPDATE CASCADE
    
    );
SELECT * FROM PAYMENT
