-- PRODUCT_PROMOTION
-- Angelo Angel

CREATE TABLE IF NOT EXISTS PRODUCT_PROMOTION (
	PROMO_CODE INT UNSIGNED,
    PROD_ID INT UNSIGNED,
    PRIMARY KEY (PROMO_CODE, PROD_ID),
    FOREIGN KEY (PROMO_CODE) REFERENCES PROMOTION (PROMO_CODE) ON DELETE CASCADE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID) ON DELETE CASCADE
);

SELECT * FROM PRODUCT_PROMOTION;