-- PRODUCT_CREATION
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS PRODUCT_CREATION(
	CREATE_ID INT UNSIGNED,
    INGRED_ID INT UNSIGNED,
    PROD_ID INT UNSIGNED,
	RECIPE_STEP_ID INT UNSIGNED,
	DATE_PERFORMED DATE NOT NULL,
    EQUIP_ID INT UNSIGNED,
    PRIMARY KEY (CREATE_ID),
    FOREIGN KEY (INGRED_ID) REFERENCES INGREDIENT (INGRED_ID) ON UPDATE CASCADE,
	FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID) ON UPDATE CASCADE,
    FOREIGN KEY (RECIPE_STEP_ID) REFERENCES RECIPE_STEP (RECIPE_STEP_ID) ON UPDATE CASCADE,
	FOREIGN KEY (EQUIP_ID) REFERENCES EQUIPMENT (EQUIP_ID) ON UPDATE CASCADE
    
    );
SELECT * FROM PRODUCT_CREATION
