-- PROMOTION
-- Angelo Angel

CREATE TABLE IF NOT EXISTS PROMOTION (
	PROMO_CODE INT UNSIGNED,
    PROMO_NAME VARCHAR(255) NOT NULL,
    PROMO_TYPE VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DISC_CODE VARCHAR(25) NOT NULL,
    DISC_RATE DECIMAL(3, 2) NOT NULL,
    LOYAL_CUST_RATE DECIMAL(3, 2),
    PRIMARY KEY (PROMO_CODE)
);