-- Rating
-- Ronaldo 

CREATE TABLE IF NOT EXISTS RATING(
RATING_CODE INT UNSIGNED,
STAR_RATING DECIMAL(2, 1) NOT NULL,
COMMENT VARCHAR(255) NOT NULL,
RATING_DATE DATE NOT NULL,
RATING_TIME TIME NOT NULL,
CUST_ID INT UNSIGNED,
PROD_ID INT UNSIGNED,
PRIMARY KEY(RATING_CODE),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE CASCADE,
FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID) ON UPDATE CASCADE
);

SELECT * FROM RATING;

