-- RECIPE
-- Angelo Angel

CREATE TABLE IF NOT EXISTS RECIPE (
	RECIPE_ID INT UNSIGNED,
    RECIPE_NAME VARCHAR(255) NOT NULL,
    RECIPE_DESC VARCHAR(255) NOT NULL,
    DATE_FOUND DATE NOT NULL,
    PRIMARY KEY (RECIPE_ID)
);

SELECT * FROM RECIPE;