-- REVIEW
-- Angelo Angel

CREATE TABLE IF NOT EXISTS REVIEW (
	REV_CODE INT UNSIGNED,
    REV_FEEDBACK VARCHAR(500) NOT NULL,
    REV_DATE DATE NOT NULL,
    REV_TIME TIME NOT NULL,
    CUST_ID INT UNSIGNED,
    PROD_ID INT UNSIGNED,
    PRIMARY KEY (REV_CODE),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE CASCADE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID) ON UPDATE CASCADE
);

SELECT * FROM REVIEW;
