-- SALARY TABLE
-- MAYBELLINE

CREATE TABLE IF NOT EXISTS SALARY(
	SALARY_ID INT UNSIGNED,
    SALARY_AMT DECIMAL (8,2) NOT NULL,
    EXPENSE_ID INT UNSIGNED,
    PRIMARY KEY(SALARY_ID),
    FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSE(EXPENSE_ID) ON UPDATE CASCADE

);

SELECT * FROM SALARY;
