-- SALES_REPORT
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS SALES_REPORT(
	REPORT_ID INT UNSIGNED,
    PAY_ID INT UNSIGNED, 
    DATE_GENERATED DATE NOT NULL,
    PRIMARY KEY (REPORT_ID),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT (PAY_ID) ON UPDATE CASCADE
    
    );
SELECT * FROM SALES_REPORT;

ALTER TABLE SALES_REPORT
ADD UNIQUE (PAY_ID);
