-- SUPPLIER
-- Angelo Angel

CREATE TABLE IF NOT EXISTS SUPPLIER (
	SUPP_ID INT UNSIGNED,
    SUPP_COMPANY VARCHAR(100) NOT NULL,
    SUPP_ADDRESS VARCHAR(255) NOT NULL,
    SUPP_PHONE_NUM VARCHAR(255) NOT NULL,
    SUPP_EMAIL VARCHAR(255) NOT NULL,
    ZIP_CODE INT UNSIGNED,
    PRIMARY KEY (SUPP_ID),
    FOREIGN KEY (ZIP_CODE) REFERENCES ZIP (ZIP_CODE) ON UPDATE CASCADE
);

SELECT * FROM SUPPLIER;
