-- TAX
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS TAX (
	TAX_ID INT UNSIGNED,
    TAX_RATE DECIMAL(5,4) NOT NULL,
    TAX_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (TAX_ID)
    );

SELECT * FROM TAX
