-- WASTE_LOG
-- VICTOR CHAVEZ

CREATE TABLE IF NOT EXISTS WASTE_LOG (
	INGRED_ID INT UNSIGNED,
    INGRED_DATE DATE NOT NULL,
    WASTE_QTY DECIMAL(5,2) NOT NULL,
    WASTE_MEASURE VARCHAR(25),
    REASON VARCHAR(25),
    PRIMARY KEY (INGRED_ID,INGRED_DATE),
    FOREIGN KEY (INGRED_ID) REFERENCES INGREDIENT (INGRED_ID) ON UPDATE CASCADE
    );
    
SELECT * FROM WASTE_LOG;

ALTER TABLE WASTE_LOG
MODIFY WASTE_QTY SMALLINT;
